# Funding file for GitHub Sponsors

github: dreamed000
patreon: dreamed000
ko_fi: dreamed000
buy_me_a_coffee: dreamed000
paypal_username: dreamed000
community_bridge: qr-shield
liberapay: dreamed000
issuehunt: dreamed000
open_collective: qr-shield
polar: dreamed000
